export const ApproveBlacklistStatus = {
    WAITING_APPROVAL_CREATE: 'WAITING_APPROVAL_CREATE',
    WAITING_APPROVAL_EDIT: 'WAITING_APPROVAL_EDIT',
    WAITING_APPROVAL_DELETE: 'WAITING_APPROVAL_DELETE',
    COMPLETED: 'COMPLETED',
    REJECTED: 'REJECTED',
}