export const CitadAccountStatus = {
    WAITING_APPROVAL_CREATE: "WAITING_APPROVAL_CREATE",
    WAITING_APPROVAL_DELETE: "WAITING_APPROVAL_DELETE",
    COMPLETED: "COMPLETED",
    REJECT: "REJECT",
    DELETED: "DELETED",
}