export const CreditNoteStatus = {
    NONE: "NONE",
    WAITING_APPROVAL: "WAITING_APPROVAL",
    WAITING_DELETE: "WAITING_DELETE",
    COMPLETED: "COMPLETED",
    DELETED: "DELETED",
    REJECTED: "REJECTED",
}