export const InternalTransferAccountStatus = {
    WAITING_APPROVAL_CREATE: "WAITING_APPROVAL_CREATE",
    WAITING_APPROVAL_DELETE: "WAITING_APPROVAL_DELETE",
    COMPLETED: "COMPLETED",
    REJECTED: "REJECTED",
}