export const paymentIdStatus = {
  WAITING_APPROVAL_CREATE: "WAITING_APPROVAL_CREATE",
  WAITING_APPROVAL_DELETE: "WAITING_APPROVAL_DELETE",
  COMPLETED: "COMPLETED",
  DELETED: "DELETED",
  REJECTED: "REJECTED"
};
