export const RequestOrderBusinessName = {
    RECEIVE_CREDIT_NOTE: 'RECEIVE_CREDIT_NOTE',
    CANCEL_CREDIT_NOTE: 'CANCEL_CREDIT_NOTE',
    CREATE_BLACKLIST_ACCOUNT: 'CREATE_BLACKLIST_ACCOUNT',
    UPDATE_BLACKLIST_ACCOUNT: 'UPDATE_BLACKLIST_ACCOUNT',
    DELETE_BLACKLIST_ACCOUNT: 'DELETE_BLACKLIST_ACCOUNT',
    CREATE_INTERNAL_TRANSFER_ACCOUNT: 'CREATE_INTERNAL_TRANSFER_ACCOUNT',
    DELETE_INTERNAL_TRANSFER_ACCOUNT: 'DELETE_INTERNAL_TRANSFER_ACCOUNT',
    EDIT_BANK_CONFIG: 'EDIT_BANK_CONFIG',
    CREATE_CITAD_ACCOUNT: 'CREATE_CITAD_ACCOUNT',
    DELETE_CITAD_ACCOUNT: 'DELETE_CITAD_ACCOUNT',
    CREATE_BANK_AMOUNT_SETTING: 'CREATE_BANK_AMOUNT_SETTING',
    DELETE_BANK_AMOUNT_SETTING: 'DELETE_BANK_AMOUNT_SETTING',
    COMPLETE_UNCOMPLETED_WITHDRAW: 'COMPLETE_UNCOMPLETED_WITHDRAW',
    REFUSE_UNCOMPLETED_WITHDRAW: 'REFUSE_UNCOMPLETED_WITHDRAW',
    UPDATE_WITHDRAW_REJECT_BY_BANK: 'UPDATE_WITHDRAW_REJECT_BY_BANK', // CẬP NHẬT KHOẢN CHI BỊ TỪ CHỐI BỜI NGÂN HÀNG
    DELETE_WITHDRAW_REJECT_BY_BANK: 'DELETE_WITHDRAW_REJECT_BY_BANK', // XÓA KHOẢN CHI BỊ TỪ CHỐI BỜI NGÂN HÀNG
}