export const RequestOrderType = {
    BANK_CONFIG: 'BANK_CONFIG',
    CITAD_ACCOUNT: 'CITAD_ACCOUNT',
    INTERBANK_NOMINAL_AMOUNT: 'INTERBANK_NOMINAL_AMOUNT',
    BLACKLIST_ACCOUNT: 'BLACKLIST_ACCOUNT',
    INTERNAL_TRANSFER_ACCOUNT: 'INTERNAL_TRANSFER_ACCOUNT',
    TRANSFER_ACCOUNTING_ERROR: 'TRANSFER_ACCOUNTING_ERROR',
    BANK_AMOUNT_SETTING: 'BANK_AMOUNT_SETTING',
    UNCOMPLETED_PAYMENT_TRANSACTION: 'UNCOMPLETED_PAYMENT_TRANSACTION',
    REJECTED_PAYMENT_TRANSACTION: "REJECTED_PAYMENT_TRANSACTION"
}