export const WithDrawRejectByBankStatus = {
    REJECT_TRANSFER_REQUEST: "REJECT_TRANSFER_REQUEST",
    WAITING_FOR_UPDATE_REJECT_TRANSFER: "WAITING_FOR_UPDATE_REJECT_TRANSFER",
    WAITING_FOR_DELETE_REJECT_TRANSFER: "WAITING_FOR_DELETE_REJECT_TRANSFER",
    SUCCESS: "SUCCESS",
}