export const WithdrawStatus = {
    INITIAL : "INITIAL",
    IN_PROGRESS : "IN_PROGRESS",
    START_RETRY : "START_RETRY",

    BANK_IS_NOT_SUPPORTED : "BANK_IS_NOT_SUPPORTED",

    BLACKLISTED_ACCOUNT : "BLACKLISTED_ACCOUNT",

    CALL_TO_GET_BANK_ACCOUNT : "CALL_TO_GET_BANK_ACCOUNT",
    ERROR_GET_BANK_ACCOUNT : "ERROR_GET_BANK_ACCOUNT",

    NAME_MISMATCH : "NAME_MISMATCH",
    AMOUNT_NOT_IN_RANGE : "AMOUNT_NOT_IN_RANGE",
    AMOUNT_NAPAS_OUT_OF_RANGE : "AMOUNT_NAPAS_OUT_OF_RANGE",

    CALL_TRANSFER_INTERNAL : "CALL_TRANSFER_INTERNAL",
    CALL_TRANSFER_EXTERNAL_CITAD : "CALL_TRANSFER_EXTERNAL_CITAD",
    CALL_TRANSFER_EXTERNAL_NAPAS : "CALL_TRANSFER_EXTERNAL_NAPAS",

    CALL_COMPLETE_TRANSFER_REQUEST : "CALL_COMPLETE_TRANSFER_REQUEST", // 1.Đánh dấu bắt đầu gọi logic hoàn tất giao dịch
    PENDING_TRANSFER_REQUEST : "PENDING_TRANSFER_REQUEST", // 1.1 Trạng thái giao dịch chi hộ chưa hoàn tất (đã chuyển tiền nhưng không cập nhật core flex)
    WAITING_FOR_UPDATE_PENDING_TRANSFER : "WAITING_FOR_UPDATE_PENDING_TRANSFER",
    WAITING_FOR_DELETE_PENDING_TRANSFER : "WAITING_FOR_DELETE_PENDING_TRANSFER",
    COMPLETE_TRANSFER_REQUEST_SUCCESSFULLY : "COMPLETE_TRANSFER_REQUEST_SUCCESSFULLY", // 2. Hoàn tất gọi logic hoàn tât giao dịch

    CALL_REJECT_TRANSFER_REQUEST : "CALL_REJECT_TRANSFER_REQUEST",
    REJECT_TRANSFER_REQUEST : "REJECT_TRANSFER_REQUEST", // Trạng thái từ chối giao dịch từ ngân hàng và chưa cập nhật vào core flex
    WAITING_FOR_UPDATE_REJECT_TRANSFER : "WAITING_FOR_UPDATE_REJECT_TRANSFER",
    WAITING_FOR_DELETE_REJECT_TRANSFER : "WAITING_FOR_DELETE_REJECT_TRANSFER",
    REJECT_TRANSFER_REQUEST_SUCCESSFULLY : "REJECT_TRANSFER_REQUEST_SUCCESSFULLY",
}